# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPJsWMXnCUuPK5yqKxtgnS9v4SM9Afs9
"""

!pip install Faker

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

n = 5000

especialidades = [
    'Medicina General',
    'Pediatría',
    'Cardiología',
    'Traumatología',
    'Ginecología',
    'Dermatología'
]

estados = [
    'Atendida',
    'Cancelada',
    'No asistió'
]

datos = []

for i in range(n):
    datos.append([
        i + 1,
        fake.date_between('-1y', 'today'),
        np.random.choice(especialidades),
        np.random.choice(estados, p=[0.75, 0.15, 0.10]),
        np.random.randint(15, 90)
    ])

df = pd.DataFrame(
    datos,
    columns=[
        'id_cita',
        'fecha',
        'especialidad',
        'estado',
        'edad'
    ]
)

df.head()

df.to_csv('citas_medicas.csv',index=False)

df = pd.read_csv('citas_medicas.csv')

df.describe()

df['especialidad'].value_counts()

df['estado'].value_counts(normalize=True)*100

df['fecha']=pd.to_datetime(df['fecha'])
df['mes']=df['fecha'].dt.month

from sklearn.linear_model import LinearRegression
import numpy as np

x=np.array(df.groupby('mes').size().index).reshape(-1,1)
y=np.array(df.groupby('mes').size().values)

modelo=LinearRegression()
modelo.fit(x,y)

prediccion=modelo.predict([[13]])

print(prediccion)

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

import pandas as pd
import plotly.express as px

df = pd.read_csv('citas_medicas.csv')

print("Dashboard de Gestión de Citas Médicas")

# Citas por Especialidad
fig1 = px.bar(
    df['especialidad'].value_counts().reset_index(),
    x='especialidad',
    y='count',
    labels={
        'especialidad': 'Especialidad',
        'count': 'Cantidad'
    },
    title='Citas por Especialidad'
)
fig1.show()

# Estado de las Citas
fig2 = px.pie(
    df,
    names='estado',
    title='Estado de las Citas'
)
fig2.show()

# Citas por Mes
df['fecha'] = pd.to_datetime(df['fecha'])
df['mes'] = df['fecha'].dt.month

citas_mes = df.groupby('mes').size().reset_index(name='cantidad')

fig3 = px.line(
    citas_mes,
    x='mes',
    y='cantidad',
    markers=True,
    title='Citas por Mes'
)
fig3.show()
